using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bsp.CommonServices.Areas.ReportData.Helps
{
    public sealed class Constantes
    {
        public const string CODIGO_PAGINA_INFORMACION_ADICIONAL = "08.01";
        public const string CODIGO_PAGINA_INFORMACION_DETALLADA = "08.02";
        public const string CODIGO_PAGINA_OTROS_REPORTES = "08.03";
        public const string CODIGO_PAGINA_POSICION_CONSOLIDADA = "08.04";
        public const string CODIGO_PAGINA_POSICION_HISTORICA = "08.05";
        public const string CODIGO_PAGINA_POSICION_TIPO_CREDITO = "08.06";
        public const string CODIGO_PAGINA_REPORTERIA_ALERTAS = "08.07";
        public const string CODIGO_PAGINA_INFORMACION_DEUDA = "08.08";

        public const string CODIGO_EMPRESA_SANTANDER = "sy_codigoEmpresaSantander";

        public const int CODIGO_TABLA_TIPO_DOCUMENTO = 101;
        public const int CODIGO_TABLA_REPORTES = 182;
        public const int CODIGO_TABLA_EMPRESAS = 181;
        public const int CODIGO_TABLA_TIPO_CREDITO = 120;
        public const int CODIGO_TABLA_TIPO_MONEDA = 186;

        public const int CODIGO_ID_RUC = 1010004;
        public const int DOCUMENTO_TRIBUTARIO_RUC = 1000002;
        public const string PAGINA_POSICION_HISTORICA = "PAGINA_POSICION_HISTORICA";
        public const string PAGINA_POSICION_CONSOLIDADA = "PAGINA_POSICION_CONSOLIDADA";
        public const string PAGINA_INFORMACION_DETALLA = "PAGINA_INFORMACION_DETALLA";

        public const string NO_ES_PAGINA_ASIGNADA = "2";
        public const string PAGINA_ASIGNADA = "1";


        //codigos de los reportes

        public const int CODIGO_REPORTE_POSICION_CONSOLIDADA = 1;
        public const int CODIGO_REPORTE_POSICION_HISTORICA = 2;
        public const int CODIGO_REPORTE_INFORMACION_DETALLADA = 3;
        public const int CODIGO_REPORTE_TIPO_CREDITO = 4;
        public const int CODIGO_REPORTE_INFORMACION_ADICIONAL = 5;
        public const int CODIGO_REPORTE_CREDITICIO_DEUDORES = 6;
        public const int CODIGO_REPORTE_CONSOLIDADO = 7;
        public const int CODIGO_REPORTE_DEUDAS = 8;
        public const int CODIGO_REPORTE_LINEAS_CREDITO = 9;

        public const int CODIGO_DEUDORES_CLASIFICACION = 10;
        public const int CODIGO_DEUDORES_DOS_O_MAS_TIPOS_DE_CREDITO = 11;
        public const int CODIGO_DEUDORES_BCP_BBVA_SCOTIABANK = 12;
        public const int CODIGO_DEUDORES_CON_CREDITOS_REFINANCIADOS = 13;
        public const int CODIGO_DEUDORES_CON_CREDITOS_VENCIDOS = 14;
        public const int CODIGO_DEUDORES_CON_CREDITOS_JUDICIALES = 15;
        public const int CODIGO_DEUDORES_CON_CREDITOS_CASTIGADOS = 16;
        public const int CODIGO_DEUDORES_SALDOS_RENDIMIENTOS_DE_CREDITO_Y_RENTAS_EN_SUSPENSO = 17;


        public const int Reporte_18 = 18;
        public const int Reporte_19 = 19;
        public const int Reporte_20 = 20;
        public const int Reporte_21 = 21;
        public const int Reporte_22 = 22;
        public const int Reporte_23 = 23;
        public const int Reporte_24 = 24;
        public const int Reporte_25 = 25;


        public const string COLUMNA_DETALLE = "ColumnaOrdena";
        public const string SESSION_DEUDOR = "SESSION_DEUDOR";

        public const string SESSION_DETALLE = "SESSION_DETALLE";
        public const string SESSION_COLUMNAS = "SESSION_COLUMNAS";

        public const string NOMBRE_REPORTE_CONSOLIDADO = "Reporte_consolidado";
        public const string NOMBRE_REPORTE_CREDITICIO = "Reporte_crediticio";


        public const string SESSION_CABECERA_DEUDOR = "SESSION_CABECERA_DEUDOR";

        public const string TITULO_REPORTE_CREDITICION_DEUDORES_LEASING = "Reporte Crediticio de Deudores Sistema Financiero - RCC";


        public const string TITULO_POSICION_TIPO_CREDITO = "Posición Por Tipo de Crédito";
        public const string SESSION_CABECERA_DEUDOR_TIPO_CREDITO = "SESSION_CABECERA_DEUDOR_TIPO_CREDITO";
        public const string SESSION_COLUMNAS_TIPO_CREDITO = "SESSION_COLUMNAS_TIPO_CREDITO";
        public const string SESSION_DETALLE_TIPO_CREDITO = "SESSION_DETALLE_TIPO_CREDITO";

        public const string TITULO_POSICION_CONSOLIDADA = "Posición consolidada";
        public const string SESSION_CABECERA_DEUDOR_POSICION_CONSOLIDADA = "SESSION_CABECERA_DEUDOR_POSICION_CONSOLIDADA";
        public const string SESSION_COLUMNAS_POSICION_CONSOLIDADA = "SESSION_COLUMNAS_POSICION_CONSOLIDADA";
        public const string SESSION_DETALLE_POSICION_CONSOLIDADA = "SESSION_DETALLE_POSICION_CONSOLIDADA";
        public const string SESSION_CABECERA_DEUDOR_INFORMACION_DEUDAS = "SESSION_CABECERA_DEUDOR_INFORMACION_DEUDAS";

        public const string SESSION_COLUMNAS_INFORMACION_LINEAS_CREDITO = "SESSION_COLUMNAS_INFORMACION_LINEAS_CREDITO";
        public const string SESSION_DETALLE_LINEAS_CREDITOS = "SESSION_DETALLE_LINEAS_CREDITOS";


        public const string TITULO_INFORMACION_ADICIONAL = "Información Adicional";
        public const string TITULO_INFORMACION_DEUDAS = "Información Deudas";

        public const string SESSION_CABECERA_DEUDOR_INFORMACION_ADICIONAL = "SESSION_CABECERA_DEUDOR_INFORMACION_ADICIONAL";
        public const string SESSION_COLUMNAS_INFORMACION_ADICIONAL = "SESSION_COLUMNAS_INFORMACION_ADICIONAL";
        public const string SESSION_DETALLE_INFORMACION_ADICIONAL = "SESSION_DETALLE_INFORMACION_ADICIONAL";
        public const string SESSION_COLUMNAS_INFORMACION_DEUDAS = "SESSION_COLUMNAS_INFORMACION_DEUDAS";
        public const string SESSION_DETALLE_INFORMACION_DEUDAS = "SESSION_DETALLE_INFORMACION_DEUDAS";


        public const string TITULO_INFORMACION_DETALLADA = "Información Detallada";
        public const string SESSION_CABECERA_DEUDOR_INFORMACION_DETALLADA = "SESSION_CABECERA_DEUDOR_INFORMACION_DETALLADA";
        public const string SESSION_COLUMNAS_INFORMACION_DETALLADA = "SESSION_COLUMNAS_INFORMACION_DETALLADA";
        public const string SESSION_DETALLE_INFORMACION_DETALLADA = "SESSION_DETALLE_INFORMACION_DETALLADA";


        public const string EXCEL_TITULO_INFORMACION_DEUDAS = "INFORMACION_DEUDAS";
        public const string EXCEL_TITULO_CREDITICIO_DE_DEUDORES_SISTEMA_FINANCIERO = "CREDITICIO_DE_DEUDORES_SISTEMA_FINANCIERO";
        public const string EXCEL_TITULO_RESUMEN_CONSOLIDADO_DEUDA = "RESUMEN_CONSOLIDADO_DEUDA";
        public const string EXCEL_TITULO_DEUDORES_CLASIFICACION = "DEUDORES_CLASIFICACION";
        public const string EXCEL_TITULO_DEUDORES_DOS_O_MAS_TIPOS_DE_CREDITO = "DEUDORES_DOS_O_MAS_TIPOS_DE_CREDITO";
        public const string EXCEL_TITULO_DEUDORES_BCP_BBVA_SCOTIABANK = "DEUDORES_BCP_BBVA_SCOTIABANK";
        public const string EXCEL_TITULO_DEUDORES_NO_SALDOS_2_O_MAS_ENTIDADES = "DEUDORES_NO_SALDOS_2_O_MAS_ENTIDADES";
        public const string EXCEL_TITULO_DEUDORES_CON_CREDITOS_VENCIDOS = "DEUDORES_CON_CREDITOS_VENCIDOS";
        public const string EXCEL_TITULO_DEUDORES_CON_CREDITOS_REFINANCIADOS = "DEUDORES_CON_CREDITOS_REFINANCIADOS";
        public const string EXCEL_TITULO_DEUDORES_CON_CREDITOS_JUDICIALES = "DEUDORES_CON_CREDITOS_JUDICIALES";
        public const string EXCEL_TITULO_DEUDORES_CON_CREDITOS_CASTIGADOS = "DEUDORES_CON_CREDITOS_CASTIGADOS";
        public const string EXCEL_TITULO_DEUDORES_SALDOS_RENDIMIENTOS_DE_CREDITO_Y_RENTAS_EN_SUSPENSO = "DEUDORES_SALDOS_RENDIMIENTOS_DE_CREDITO_Y_RENTAS_EN_SUSPENSO";


        public const string EXCEL_TITULO_INCREMENTO_LEASEBACK_RESPECTO_MES_ANTERIOR = "INCREMENTO_LEASEBACK_RESPECTO_MES_ANTERIOR";
        public const string EXCEL_TITULO_BANCO_SANTANDER_PARTICIPACIÓN_MAYOR_20_DEL_TOTAL_SALDO = "BANCO_SANTANDER_PARTICIPACIÓN_MAYOR_20%_DEL_TOTAL_SALDO";
        public const string EXCEL_TITULO_INCREMENTO_DEUDA_DIRECTA_Y_DISMINUCIÓN_DEUDA_INDIRECTA = "INCREMENTO_DEUDA_DIRECTA_Y_DISMINUCIÓN_DEUDA_INDIRECTA";
        public const string EXCEL_TITULO_PRODUCTO_SOBREGIRO_MAYOR_5_DEUDA_DIRECTA = "PRODUCTO_SOBREGIRO_MAYOR_5%_DEUDA_DIRECTA";
        public const string EXCEL_TITULO_INCREMENTO_MAYOR_A_20_RESPECTO_MES_ANTERIOR_Y_MAYOR_50_12_MESES = "INCREMENTO_MAYOR_A_20%_RESPECTO_MES_ANTERIOR_Y_MAYOR_50%_12_MESES";
        public const string EXCEL_TITULO_INCREMENTO_MAYOR_A_20_PRESTAMO_MES_ANTERIOR_Y_MAYOR_50_12_MESES = "INCREMENTO_MAYOR_A_20%_PRÉSTAMO_MES ANTERIOR_Y_MAYOR_50%_12_MESES";
        public const string EXCEL_TITULO_INCREMENTO_MAYOR_A_20_GT_PREFERIDAS_MES_ANTERIOR_Y_MAYOR_50_12_MESES = "INCREMENTO_MAYOR_A_20%_GT_PREFERIDAS_MES_ANTERIOR_Y_MAYOR_50%_12_MESES";
        public const string EXCEL_TITULO_DEUDORES_DIAS_DE_ATRASO = "DEUDORES_DÍAS_DE_ATRASO";

    }
}